# fly.toml app configuration file generated for kviecio-grudas on 2025-02-11T21:05:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kviecio-grudas'
primary_region = 'waw'

[build.args]
  PB_VERSION="0.24.4"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"